### ISSUE TITLE
Share animation effects.

### ISSUE THREAD

**Issue by createWheel** [emilkowalski/css-effects-snippets#12]
```css
  * {
        box-sizing: border-box;
      }
      *::before,
      *::after {
        box-sizing: border-box;
      }
      .box {
        width: 120px;
        height: 50px;
        line-height: 50px;
        position: relative;
        text-align: center;
        cursor: pointer;
      }
      .box::before {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        content: "";
        border-left: 1px solid #ccc;
        border-top: 1px solid #ccc;
        -webkit-transform: scale(0);
        -ms-transform: scale(0);
        transform: scale(0);
        transform-origin: left top;
        -webkit-transition: -webkit-transform 0.5s;
        transition: -webkit-transform 0.5s;
        -o-transition: transform 0.5s;
        transition: transform 0.5s;
        transition: transform 0.5s, -webkit-transform 0.5s;
      }
      .box::after {
        position: absolute;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        content: "";
        border-right: 1px solid #ccc;
        border-bottom: 1px solid #ccc;
        -webkit-transform: scale(0);
        -ms-transform: scale(0);
        transform: scale(0);
        transform-origin: right bottom;
        -webkit-transition: -webkit-transform 0.5s;
        transition: -webkit-transform 0.5s;
        -o-transition: transform 0.5s;
        transition: transform 0.5s;
        transition: transform 0.5s, -webkit-transform 0.5s;
      }
      .box:hover::before {
        -webkit-transform: scale(1);
        -ms-transform: scale(1);
        transform: scale(1);
      }
      .box:hover::after {
        -webkit-transform: scale(1);
        -ms-transform: scale(1);
        transform: scale(1);
      }
```
```html
<div class="box">Hover me</div>
```
end.    :)
